services:
  plc_m340:
    image: conpot/conpot
    container_name: plc_m340
    volumes:
      - ./conpot/config.json:/opt/conpot/config.json
    command: ["conpot", "-c", "/opt/conpot/config.json"]
    networks:
      ot-net:
        ipv4_address: 192.168.20.10
    ports:
      - "502:502"  

  scada_hmi:
    build: ./scada
    container_name: scada_hmi
    networks:
      ot-net:
        ipv4_address: 192.168.20.20
    depends_on:
      - plc_m340

  ot_gateway:
    image: alpine
    container_name: ot_gateway
    command: tail -f /dev/null
    networks:
      ot-net:
        ipv4_address: 192.168.20.99
    # plus tard ajouter aussi red-net / blue-net

networks:
  ot-net:
    driver: bridge
    internal: true  # air-gapped
    ipam:
      config:
        - subnet: 192.168.20.0/24
