networks:
  ot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24

services:
  plc1:
    build: ./plc1
    networks:
      ot-net:
        ipv4_address: 192.168.20.10
    restart: unless-stopped

  scada_hmi:
    build: ./scada_hmi
    networks:
      ot-net:
        ipv4_address: 192.168.20.20
    depends_on:
      - plc1
    restart: unless-stopped

  ot_gateway:
    image: alpine
    command: tail -f /dev/null
    networks:
      ot-net:
        ipv4_address: 192.168.20.254
    restart: unless-stopped